[project]
name = "market"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.5.0",
    "plotly>=5.24.1",
    "yfinance>=0.2.48",
]

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ruff>=0.7.3",
]
